rootProject.name = "psinder"

include(":application:main")
include(":application:shared")
include(":application:test-utils")
include(":application:mediator")
include(":application:monitoring")
include(":application:event-store")
include(":application:event-store:event-store-contract")
include(":application:mongo-db-access")
include(":application:account")
include(":application:account:account-contract")
include(":application:security")
include(":application:security:security-contract")
include(":application:mail")
include(":application:mail:mail-contract")
include(":application:feature-toggle")
include(":application:feature-toggle:feature-toggle-contract")
include(":application:dog")
include(":application:dog:dog-contract")
include(":application:aws")
include(":application:aws:aws-contract")
include(":application:file-storage")
include(":application:file-storage:file-storage-contract")
