version: "3.4"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret_password
      MONGO_INITDB_DATABASE: psinder

  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  localstack:
    image: localstack/localstack:0.12.16
    container_name: localstack
    environment:
      - SERVICES=sqs,sns,sts,cloudformation,ec2,iam,s3
      - DEFAULT_REGION=eu-north-1
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "4566:4566"
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  localstack-bootstrap:
    image: node:17.9
    user: node
    working_dir: /app
    volumes:
      - ../.aws-cdk:/app
    environment:
      DEPLOY_ENV: dev
      LOCALSTACK_HOSTNAME: localstack
      AWS_ACCOUNT_ID: '000000000000'
      AWS_DEFAULT_REGION: eu-north-1
      AWS_ACCESS_KEY_ID: test
      AWS_ACCESS_KEY_SECRET: test
      AWS_REGION: eu-north-1
    command: sh -lc "npm i && npm run cdklocal:deploy"

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
