name: Build test

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: psinder

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build with Gradle
        env:
          SONAR_LOGIN_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          ./gradlew detektAllSneaky 
          ./gradlew ktlintCheck 
          ./gradlew jacocoRootReport 
          ./gradlew sonarqube
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: **/test-results/**/*.xml

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: KtLint Scripts
        run: ./gradlew ktlintKotlinScriptCheck

      - name: KtLint Sources
        run: ./gradlew ktlintMainSourceSetCheck

      - name: KtLint Tests
        run: ./gradlew ktlintTestSourceSetCheck

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Detekt checks
        run: ./gradlew detektAll

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build with Gradle
        run: ./gradlew test
